//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paws.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paws.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feral.
        /// </summary>
        internal static string AbilityChainsControl_editItemToolStripMenuItem_Click_Feral {
            get {
                return ResourceManager.GetString("AbilityChainsControl_editItemToolStripMenuItem_Click_Feral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string AbilityChainsControl_removeSelectedItemsButton_Click_Warning {
            get {
                return ResourceManager.GetString("AbilityChainsControl_removeSelectedItemsButton_Click_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not press any modifier keys such as Control, Shift, and Alt.
        ///Use the Checkboxes to assign those keys.
        /// </summary>
        internal static string AddNewAbilityChainForm_AddNewAbilityChainForm_KeyUp_ {
            get {
                return ResourceManager.GetString("AddNewAbilityChainForm_AddNewAbilityChainForm_KeyUp_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Key Now.
        /// </summary>
        internal static string AddNewAbilityChainForm_hotKeyTriggerSetKeyButton_Click_Press_Key_Now {
            get {
                return ResourceManager.GetString("AddNewAbilityChainForm_hotKeyTriggerSetKeyButton_Click_Press_Key_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Key.
        /// </summary>
        internal static string AddNewAbilityChainForm_hotKeyTriggerSetKeyButton_Click_Set_Key {
            get {
                return ResourceManager.GetString("AddNewAbilityChainForm_hotKeyTriggerSetKeyButton_Click_Set_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string AddNewAbilityChainForm_removeSelectedAbilitiesButton_Click_Warning {
            get {
                return ResourceManager.GetString("AddNewAbilityChainForm_removeSelectedAbilitiesButton_Click_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string AddNewAbilityChainForm_saveButton_Click_Error {
            get {
                return ResourceManager.GetString("AddNewAbilityChainForm_saveButton_Click_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability chain name text box cannot be blank..
        /// </summary>
        internal static string AddNewAbilityChainForm_saveButton_Click_The_ability_chain_name_text_box_cannot_be_blank_ {
            get {
                return ResourceManager.GetString("AddNewAbilityChainForm_saveButton_Click_The_ability_chain_name_text_box_cannot_be" +
                        "_blank_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hot key must be set..
        /// </summary>
        internal static string AddNewAbilityChainForm_saveButton_Click_The_hot_key_must_be_set_ {
            get {
                return ResourceManager.GetString("AddNewAbilityChainForm_saveButton_Click_The_hot_key_must_be_set_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one ability..
        /// </summary>
        internal static string AddNewAbilityChainForm_saveButton_Click_There_must_be_at_least_one_ability_ {
            get {
                return ResourceManager.GetString("AddNewAbilityChainForm_saveButton_Click_There_must_be_at_least_one_ability_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Ability..
        /// </summary>
        internal static string AddNewAbilityForm_saveButton_Click_Please_select_an_Ability_ {
            get {
                return ResourceManager.GetString("AddNewAbilityForm_saveButton_Click_Please_select_an_Ability_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string AddNewAbilityForm_saveButton_Click_Warning {
            get {
                return ResourceManager.GetString("AddNewAbilityForm_saveButton_Click_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no parameters required for this condition..
        /// </summary>
        internal static string AddNewConditionForm_conditionsComboBox_SelectedIndexChanged_There_are_no_parameters_required_for_this_condition_ {
            get {
                return ResourceManager.GetString("AddNewConditionForm_conditionsComboBox_SelectedIndexChanged_There_are_no_paramete" +
                        "rs_required_for_this_condition_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Condition..
        /// </summary>
        internal static string AddNewConditionForm_saveButton_Click_Please_select_a_Condition_ {
            get {
                return ResourceManager.GetString("AddNewConditionForm_saveButton_Click_Please_select_a_Condition_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string AddNewConditionForm_saveButton_Click_Warning {
            get {
                return ResourceManager.GetString("AddNewConditionForm_saveButton_Click_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string AddNewItemForm_removeSelectedConditionsButton_Click_Warning {
            get {
                return ResourceManager.GetString("AddNewItemForm_removeSelectedConditionsButton_Click_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string AddNewItemForm_saveButton_Click_Notice {
            get {
                return ResourceManager.GetString("AddNewItemForm_saveButton_Click_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an item id to continue..
        /// </summary>
        internal static string AddNewItemForm_saveButton_Click_You_must_enter_an_item_id_to_continue_ {
            get {
                return ResourceManager.GetString("AddNewItemForm_saveButton_Click_You_must_enter_an_item_id_to_continue_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an item name to continue..
        /// </summary>
        internal static string AddNewItemForm_saveButton_Click_You_must_enter_an_item_name_to_continue_ {
            get {
                return ResourceManager.GetString("AddNewItemForm_saveButton_Click_You_must_enter_an_item_name_to_continue_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;False&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;True&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;False&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;False&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;True&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWild [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Automated_Battlegrounds {
            get {
                return ResourceManager.GetString("Automated_Battlegrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;False&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;True&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;True&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;True&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;True&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWildCh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Automated_Dungeons {
            get {
                return ResourceManager.GetString("Automated_Dungeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;True&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;False&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;False&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;False&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;True&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWild [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Automated_Questing {
            get {
                return ResourceManager.GetString("Automated_Questing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;False&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;True&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;True&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;True&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;True&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWildCh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Manual_Arena {
            get {
                return ResourceManager.GetString("Manual_Arena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;True&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;False&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;True&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;True&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;False&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWildC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Manual_Battlegrounds {
            get {
                return ResourceManager.GetString("Manual_Battlegrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;True&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;False&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;True&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;True&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;False&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWildC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Manual_Dungeons {
            get {
                return ResourceManager.GetString("Manual_Dungeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;True&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;False&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;True&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;True&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;False&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWildC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Manual_Questing {
            get {
                return ResourceManager.GetString("Manual_Questing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;False&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;True&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;True&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;True&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;True&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWildCh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Manual_Raiding {
            get {
                return ResourceManager.GetString("Manual_Raiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;False&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;False&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;True&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;True&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;True&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;False&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWild [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Minimalist {
            get {
                return ResourceManager.GetString("Minimalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feral.
        /// </summary>
        internal static string SettingsForm_InitSettingsMode_Feral {
            get {
                return ResourceManager.GetString("SettingsForm_InitSettingsMode_Feral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian.
        /// </summary>
        internal static string SettingsForm_InitSettingsMode_Guardian {
            get {
                return ResourceManager.GetString("SettingsForm_InitSettingsMode_Guardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string SettingsForm_itemsDisableCheckedItemsButton_Click_Disabled {
            get {
                return ResourceManager.GetString("SettingsForm_itemsDisableCheckedItemsButton_Click_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string SettingsForm_itemsEnableCheckedItemsButton_Click_Enabled {
            get {
                return ResourceManager.GetString("SettingsForm_itemsEnableCheckedItemsButton_Click_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string SettingsForm_itemsRemoveSelectedItemsButton_Click_Warning {
            get {
                return ResourceManager.GetString("SettingsForm_itemsRemoveSelectedItemsButton_Click_Warning", resourceCulture);
            }
        }
    }
}
