//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paws.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paws.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;False&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;True&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;False&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;False&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;True&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWildCh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Automated_Battlegrounds {
            get {
                return ResourceManager.GetString("Automated_Battlegrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;False&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;True&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;True&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;True&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;True&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWildChar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Automated_Dungeons {
            get {
                return ResourceManager.GetString("Automated_Dungeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;True&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;False&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;False&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;False&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;True&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWildCh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Automated_Questing {
            get {
                return ResourceManager.GetString("Automated_Questing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;False&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;True&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;True&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;True&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;True&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWildChar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Manual_Arena {
            get {
                return ResourceManager.GetString("Manual_Arena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;True&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;False&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;True&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;True&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;False&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWildCha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Manual_Battlegrounds {
            get {
                return ResourceManager.GetString("Manual_Battlegrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;True&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;False&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;True&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;True&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;False&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWildCha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Manual_Dungeons {
            get {
                return ResourceManager.GetString("Manual_Dungeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;True&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;False&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;True&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;True&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;False&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWildCha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Manual_Questing {
            get {
                return ResourceManager.GetString("Manual_Questing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;True&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;False&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;True&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;True&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;True&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;True&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWildChar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Manual_Raiding {
            get {
                return ResourceManager.GetString("Manual_Raiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SettingsManager&gt;
        ///  &lt;BearFormEnabled&gt;False&lt;/BearFormEnabled&gt;
        ///  &lt;BearFormOnlyDuringPullOrCombat&gt;False&lt;/BearFormOnlyDuringPullOrCombat&gt;
        ///  &lt;BearFormAlways&gt;True&lt;/BearFormAlways&gt;
        ///  &lt;BearFormDoNotOverrideCatForm&gt;True&lt;/BearFormDoNotOverrideCatForm&gt;
        ///  &lt;BearFormDoNotOverrideTravelForm&gt;True&lt;/BearFormDoNotOverrideTravelForm&gt;
        ///  &lt;GuardianWildChargeEnabled&gt;False&lt;/GuardianWildChargeEnabled&gt;
        ///  &lt;GuardianWildChargeMinDistance&gt;10&lt;/GuardianWildChargeMinDistance&gt;
        ///  &lt;GuardianWildCh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Minimalist {
            get {
                return ResourceManager.GetString("Minimalist", resourceCulture);
            }
        }
    }
}
